import os
from openai import OpenAI
import time
import random

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key="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",
)

SYSTEM_PROMPT = """
You are a regular crypto enthusiast hanging out on Twitter, replying to posts from other crypto folks. 
Your replies must sound completely natural, as if written by a real person, NOT an AI. Don't put spaces after dots and commas
Keep your replies short and to the point — 1 to 3 sentences, no overthinking or complicated words. Also you can ask reasonable questions.
Do NOT use emojis. Use crypto slang but not too much. If you use slang,use it only IN APPROPRIATE PLACES!!!
If you see some angry content that violates your rules, give simple answer, that barely connects to the tweet.
Avoid clichés, repeated phrases, or overly formal language — each reply should feel fresh and unique. You even can make small grammar mistakes.
Don't use dashes or lots of spaces, and don't use quotes very often, if you can avoid them at all.Don't put space after comma.

The tone of your replies depends on the specified style:
- friendly — warm, supportive, like talking to a crypto buddy,
- strict — blunt, direct, no sugarcoating,
- ironic — sarcastic and teasing, but not mean-spirited.

The main goal is for your replies to sound exactly like real crypto community members commenting on Twitter, not like something generated by a bot.
"""

def generate_reply(tweet_text: str, settings: dict, **extra):
    """
    Генерация ответа на твит с гарантией полного текста
    :param tweet_text: текст твита
    :param settings: словарь с настройками (tone, min_reply_delay, max_reply_delay)
    :param extra: model, temperature, max_tokens и др.
    :return: dict { "tweet": ..., "reply": ..., "tone": ..., "model": ... }
    """
    tone = settings.get("tone", "friendly")
    model = extra.get("model", "openai/gpt-oss-120b:cerebras")
    temperature = extra.get("temperature", 0.8)
    max_tokens = extra.get("max_tokens", 400)  # увеличено для длинных ответов
    retries = 5
    full_reply = ""

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "assistant", "content": f"Тон общения: {tone}"},
        {"role": "user", "content": f"Твит: {tweet_text}"},
    ]

    for attempt in range(1, retries + 1):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=messages,
                max_tokens=max_tokens,
                temperature=temperature,
            )
            choice = response.choices[0]
            content = getattr(choice.message, "content", "")
            finish_reason = getattr(choice, "finish_reason", "stop")

            if content:
                full_reply += content.strip()

            if finish_reason == "stop" and full_reply:
                break  # ответ полностью сгенерирован
            else:
                wait_time = random.uniform(5, 10) * attempt
                print(f"⚠️ Попытка {attempt} не завершена (finish_reason={finish_reason}), повтор через {wait_time:.1f} сек...")
                time.sleep(wait_time)
        except Exception as e:
            wait_time = random.uniform(5, 10) * attempt
            print(f"❌ Попытка {attempt} завершилась ошибкой: {e}, повтор через {wait_time:.1f} сек...")
            time.sleep(wait_time)

    # fallback на короткий безопасный ответ
    if not full_reply or len(full_reply.strip()) < 15:
        full_reply = "OK your are strange kinda"

    return {"tweet": tweet_text, "reply": full_reply.strip(), "tone": tone, "model": model}


# Пример использования
if __name__ == "__main__":
    tweet = "Lost a lot of money this month, tell me your ways to pass this bad time, your methods to overcome this"
    settings = {"tone": "friendly", "min_reply_delay": 10, "max_reply_delay": 120}

    result = generate_reply(tweet, settings)
    print("📌 Твит:", result["tweet"])
    print("💬 Ответ:", result["reply"])
